### ISSUE TITLE
Speed limit changes only work in one direction

### ISSUE THREAD

**Issue by perreira** [FPLedit/FPLedit#27]
Speed limit changes are only displayed correctly in "Buchfahrplan" for the journey in one direction, returning trains have limit steps in wrong order and end/beginning are not reversed as they should See example file attached.
[for-ber-test.zip](https://github.com/FPLedit/FPLedit/files/10418037/for-ber-test.zip)

**Comment by ManuelHu** [comment]
Fixed in c279c11e57d32d7f60b93ad9387d6905b03ee799.

This will be in the next stable release 2.5.0,   
or - after I fix the CI job that is currently failing - available as download from GitHub actions.
