### ISSUE TITLE
Trains can only be added in one direction

### ISSUE THREAD

**Issue by perreira** [FPLedit/FPLedit#29]
In FOR-BER file (see previous issue) I tried to add a train NFOR to NEBM, in the train adding form the timetable can only be given in one direction. For the return direction the "Ankunft" in NFOR is not possible to be filled out.

**Comment by ManuelHu** [comment]
If this is a bug, it will be fixed for 2.5.0. but I am not sure if this is just the current intended behaviour.

Maybe there is a slight misunderstanding about FPLedit's inner workings: On a linear timetable (like in your example file), trains only have one direction. It is not possible for a train to return. For the return direction, a new train (with a different name) has to be created.
This also means that no "Ankuft" can be filled out at the first station, as well as no "Abfahrt" at the last one. This of course only applies in the direction of the train - of course it _should_ be certainly possible to fill out the abfahrt at the first station of a returning train.

This is unfortunately something that I cannot fix, as this is a limitation of the timetable file format of linear lines (which I cannot change for interoperability with other applications...).

It would be helpful to know if the described bug is just this (unfortunate) behavior, or if there is still something broken beyond that... Thanks :-)

---

Note that it _should_ be possible to select a next train that continues the travel, which will than be marked in the Bildfahrplan. But this functionality is currently broken... And it does not produce any output in the generated HTML timetables.

**Comment by perreira** [comment]
Please close this bug, this was user error (I did not find the second "Add train" button, which was prominently displayed...). sorry for the confusion.

**Comment by perreira** [comment]
Ah, I can close it myself... Done
