### ISSUE TITLE
Feature Request: Different colours in Graphic Timetable

### ISSUE THREAD

**Issue by NicolasMUC** [FPLedit/FPLedit#34]
A very nice feature would be the option to assign a specific colour to a train which will be used to draw this trains line in the "Bildfahrplan". I guess the easiest way would be to allow the user to choose the colour when "creating" the train in the Timetable editor.

**Comment by ManuelHu** [comment]
Thanks for the feature request. This is already implemented, but the feature is hidden and can only be enabled manually.

1. Close FPLedit
2. Open the file `fpledit.conf` from the program directory with a text editor
3. Add a line at the end
    ```
    feature.enable-full-graph-editor="true"
    ```
5. Save the config file and close the text editor
6. Re-start FPLedit
7. to enable the individual styling of trains (and stations), you have to uncheck "Verwende nur Plandarstellung" in the Bildfrahplan menu

note however, that many of the hidden features are not well-tested (i.e. the PDF export), but they should be usable.

If you have any additional questions, feel free to ask :-)

**Comment by lifeonmonday** [comment]
Is there a way to activate this on macOS as well? :)

**Comment by ManuelHu** [comment]
technically the config file mentioned here also exists on macOS, the location is just different. On macOS the config file is not stored alongside the application files, but inside a user directory.

I would need to look it up - as I don't have a macOS device here, I do not know the location from the top of my head.

**Comment by lifeonmonday** [comment]
Thanks so much for a reply. Based on your tip I’ve found it ~/Library/Application Support/de.fpledit.FPLedit
Thank you!
