### ISSUE TITLE
Graphical Timetable: "Height per hour" setting has no effect

### ISSUE THREAD

**Issue by rsrmean** [FPLedit/FPLedit#37]
When trying to change the "height per hour" setting, the graphical timetable ist not changed. Addtionally, when opening the "Change Plan Display" menu again, the setting is being reset to 150.

**Comment by ManuelHu** [comment]
thanks for the report, and sorry for me taking so long to reply.

The issue should be fixed in f54b7803b7ea21fde6346498bc5a3c608fc5c0b2, which is included in the freshly released FPLedit version 2.6.4.
